Name: Sahil Suresh Ghogare

Roll no.: 23102A0061

Branch / Div: BE CMPN A

R_Assignment-2_Lab 3

**Installing R packages**

In [ ]:
install.packages("tidyverse")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

**Loading Libraries**

In [ ]:
library(tidyverse)

**Loading the Heart Disease dataset**

In [ ]:
unzip(
  "/content/heart+disease.zip",
  exdir = "/content/heart_disease"
)

print("Dataset extracted successfully!")

[1] "Dataset extracted successfully!"

In [ ]:
list.files("/content/heart_disease")

 [1] "ask-detrano"                "bak"
 [3] "cleve.mod"                  "cleveland.data"
 [5] "costs"                      "heart-disease.names"
 [7] "hungarian.data"             "Index"
 [9] "long-beach-va.data"         "new.data"
[11] "processed.cleveland.data"   "processed.hungarian.data"
[13] "processed.switzerland.data" "processed.va.data"
[15] "reprocessed.hungarian.data" "switzerland.data"
[17] "WARNING"

In [ ]:
data <- read.csv(
  "/content/heart_disease/processed.cleveland.data",
  header = FALSE,
  na.strings = "?"
)

colnames(data) <- c(
  "age",
  "sex",
  "cp",
  "trestbps",
  "chol",
  "fbs",
  "restecg",
  "thalach",
  "exang",
  "oldpeak",
  "slope",
  "ca",
  "thal",
  "num"
)

head(data)

  age sex cp trestbps chol fbs restecg thalach exang oldpeak slope ca thal num
1 63  1   1  145      233  1   2       150     0     2.3     3     0  6    0
2 67  1   4  160      286  0   2       108     1     1.5     2     3  3    2
3 67  1   4  120      229  0   2       129     1     2.6     2     2  7    1
4 37  1   3  130      250  0   0       187     0     3.5     3     0  3    0
5 41  0   2  130      204  0   2       172     0     1.4     1     0  3    0
6 56  1   2  120      236  0   0       178     0     0.8     1     0  3    0

**Checking Dataset**

In [ ]:
cat("Number of rows:", nrow(data), "\n")
cat("Number of columns:", ncol(data), "\n")

str(data)
summary(data)

Number of rows: 303
Number of columns: 14
'data.frame':	303 obs. of  14 variables:
 $ age     : num  63 67 67 37 41 56 62 57 63 53 ...
 $ sex     : num  1 1 1 1 0 1 0 0 1 1 ...
 $ cp      : num  1 4 4 3 2 2 4 4 4 4 ...
 $ trestbps: num  145 160 120 130 130 120 140 120 130 140 ...
 $ chol    : num  233 286 229 250 204 236 268 354 254 203 ...
 $ fbs     : num  1 0 0 0 0 0 0 0 0 1 ...
 $ restecg : num  2 2 2 0 2 0 2 0 2 2 ...
 $ thalach : num  150 108 129 187 172 178 160 163 147 155 ...
 $ exang   : num  0 1 1 0 0 0 0 1 0 1 ...
 $ oldpeak : num  2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 ...
 $ slope   : num  3 2 2 3 1 1 3 1 2 3 ...
 $ ca      : num  0 3 2 0 0 0 2 0 1 0 ...
 $ thal    : num  6 3 7 3 3 3 3 3 7 7 ...
 $ num     : int  0 2 1 0 0 0 3 0 2 1 ...

      age             sex               cp           trestbps
 Min.   :29.00   Min.   :0.0000   Min.   :1.000   Min.   : 94.0
 1st Qu.:48.00   1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:120.0
 Median :56.00   Median :1.0000   Median :3.000   Median :130.0
 Mean   :54.44   Mean   :0.6799   Mean   :3.158   Mean   :131.7
 3rd Qu.:61.00   3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:140.0
 Max.   :77.00   Max.   :1.0000   Max.   :4.000   Max.   :200.0

      chol            fbs            restecg          thalach
 Min.   :126.0   Min.   :0.0000   Min.   :0.0000   Min.   : 71.0
 1st Qu.:211.0   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:133.5
 Median :241.0   Median :0.0000   Median :1.0000   Median :153.0
 Mean   :246.7   Mean   :0.1485   Mean   :0.9901   Mean   :149.6
 3rd Qu.:275.0   3rd Qu.:0.0000   3rd Qu.:2.0000   3rd Qu.:166.0
 Max.   :564.0   Max.   :1.0000   Max.   :2.0000   Max.   :202.0

     exang           oldpeak         slope             ca
 Min.   :0.0000   Min.   :0.00   Min.   :1.000   Min.   :0.0000
 1st Qu.:0.0000   1st Qu.:0.00   1st Qu.:1.000   1st Qu.:0.0000
 Median :0.0000   Median :0.80   Median :2.000   Median :0.0000
 Mean   :0.3267   Mean   :1.04   Mean   :1.601   Mean   :0.6722
 3rd Qu.:1.0000   3rd Qu.:1.60   3rd Qu.:2.000   3rd Qu.:1.0000
 Max.   :1.0000   Max.   :6.20   Max.   :3.000   Max.   :3.0000
                                                 NAs    :4
      thal            num
 Min.   :3.000   Min.   :0.0000
 1st Qu.:3.000   1st Qu.:0.0000
 Median :3.000   Median :0.0000
 Mean   :4.734   Mean   :0.9373
 3rd Qu.:7.000   3rd Qu.:2.0000
 Max.   :7.000   Max.   :4.0000
 NAs    :2

**Introducing Data-Entry Problems**

In [ ]:
data$trestbps[1] <- -120
data$trestbps[2] <- -90
data$trestbps[3] <- NA
data$trestbps[4] <- 320
data$trestbps[5] <- 350

data$trestbps[1:10]

 [1] -120  -90   NA  320  350  120  140  120  130  140

**Creating BP Cleaning Function**

In [ ]:
clean_bp <- function(bp) {

  if (is.na(bp)) {
    return(NA)

  } else if (bp < 0) {
    return(NA)

  } else if (bp > 250) {
    return(250)

  } else {
    return(bp)
  }
}

**Testing the function**

In [ ]:
test_values <- c(-100, NA, 120, 200, 300, 350)

sapply(test_values, clean_bp)

[1]  NA  NA 120 200 250 250

**Applying the cleaning function**

In [ ]:
data$trestbps_clean <- sapply(
  data$trestbps,
  clean_bp
)

head(data[, c("trestbps", "trestbps_clean")], 10)

   trestbps trestbps_clean
1  -120      NA
2   -90      NA
3    NA      NA
4   320     250
5   350     250
6   120     120
7   140     140
8   120     120
9   130     130
10  140     140

**Error Handling using tryCatch()**

In [ ]:
safe_mean_bp <- function(bp) {

  tryCatch({

    if (all(is.na(bp))) {
      stop("All BP values are missing.")
    }

    mean(bp, na.rm = TRUE)

  }, warning = function(w) {
    message("Warning: ", w$message)
    NA
  }, error = function(e) {
    message("Error: ", e$message)
    NA
  })
}

In [ ]:
mean_bp <- safe_mean_bp(data$trestbps_clean)

cat("Mean cleaned BP:", mean_bp, "\n")

Mean cleaned BP: 132.39

**Cholesterol / BP Ratio**

In [ ]:
safe_ratio <- function(chol, bp) {

  tryCatch({

    if (is.na(chol) || is.na(bp)) {
      stop("Cholesterol or BP is missing.")
    }

    if (bp <= 0) {
      stop("BP denominator must be greater than zero.")
    }

    chol / bp

  }, error = function(e) {
    message("Invalid ratio: ", e$message)
    NA
  })
}

In [ ]:
ratio1 <- safe_ratio(200, 120)
ratio2 <- safe_ratio(250, 0)
ratio3 <- safe_ratio(220, NA)
ratio4 <- safe_ratio(200, -50)

cat("Ratio 1:", ratio1, "\n")
cat("Ratio 2:", ratio2, "\n")
cat("Ratio 3:", ratio3, "\n")
cat("Ratio 4:", ratio4, "\n")

Invalid ratio: BP denominator must be greater than zero.

Invalid ratio: Cholesterol or BP is missing.

Invalid ratio: BP denominator must be greater than zero.

Ratio 1: 1.666667
Ratio 2: NA
Ratio 3: NA
Ratio 4: NA

**Loop-Based Cleaning**

In [ ]:
bp_loop <- data$trestbps

start_loop <- Sys.time()

for (i in 1:length(bp_loop)) {

  if (is.na(bp_loop[i])) {
    next

  } else if (bp_loop[i] < 0) {
    bp_loop[i] <- NA

  } else if (bp_loop[i] > 250) {
    bp_loop[i] <- 250
  }
}

end_loop <- Sys.time()

loop_time <- end_loop - start_loop

bp_loop[1:10]

 [1]  NA  NA  NA 250 250 120 140 120 130 140

**Vectorized Cleaning**

In [ ]:
bp_vectorized <- data$trestbps

start_vector <- Sys.time()

bp_vectorized[bp_vectorized < 0] <- NA

bp_vectorized[bp_vectorized > 250] <- 250

end_vector <- Sys.time()

vector_time <- end_vector - start_vector

bp_vectorized[1:10]

 [1]  NA  NA  NA 250 250 120 140 120 130 140

**Comparing Execution Time**

In [ ]:
comparison <- data.frame(
  Method = c("For Loop", "Vectorized"),
  Execution_Time = c(
    as.numeric(loop_time),
    as.numeric(vector_time)
  )
)

comparison

  Method     Execution_Time
1 For Loop   0.018310785
2 Vectorized 0.005909681

**Validating Cleaned Data**

In [ ]:
cleaned_bp <- bp_vectorized

missing_count <- sum(is.na(cleaned_bp))

minimum_bp <- min(cleaned_bp, na.rm = TRUE)

maximum_bp <- max(cleaned_bp, na.rm = TRUE)

mean_bp <- mean(cleaned_bp, na.rm = TRUE)

median_bp <- median(cleaned_bp, na.rm = TRUE)

cat("Missing BP values:", missing_count, "\n")
cat("Minimum BP:", minimum_bp, "\n")
cat("Maximum BP:", maximum_bp, "\n")
cat("Mean BP:", mean_bp, "\n")
cat("Median BP:", median_bp, "\n")

Missing BP values: 3
Minimum BP: 94
Maximum BP: 250
Mean BP: 132.39
Median BP: 130

**Verifying No Invalid Values Remain**

In [ ]:
negative_values <- sum(cleaned_bp < 0, na.rm = TRUE)

values_above_250 <- sum(cleaned_bp > 250, na.rm = TRUE)

cat("Negative BP values:", negative_values, "\n")
cat("BP values greater than 250:", values_above_250, "\n")

Negative BP values: 0
BP values greater than 250: 0

**Saving Cleaned Dataset**

In [ ]:
data$trestbps <- cleaned_bp

data$trestbps_clean <- NULL

write.csv(
  data,
  "cleaned_heart_data.csv",
  row.names = FALSE
)

cat("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

The vectorized method is more efficient than the for loop because it generally executes the cleaning operation faster and with less code, especially for larger datasets.